@startuml
'https://plantuml.com/class-diagram

skinparam classAttributeIconSize 0


class Prodotto{
    -nome: String
    -codice:int
    -quantitaInMagazzino: int
    -prezzo:double

    +Prodotto(String nome, int codice, int quantitaInMagazzino, double prezzo)
    +get_nome():String
    +set_nome(string)
    +get_codice():int
    +set_codice(int)
    +get_quantitaInMagazzino():int
    +set_quantitaInMagazzino(int)
    +get_prezzo():double
    +set_prezzo(double)
    +aggiornaQuantita(int qt):void
    +calcolaTotale():void
}
@enduml